global:
  scrape_interval: 8s
  evaluation_interval: 8s

scrape_configs:
  - job_name: 'job-prometheus'
    scrape_interval: 9s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "job-node-exporter"
    scrape_interval: 9s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: 'job-nodejs'  # (แนะนำ เปลี่ยนชื่อเล็กน้อยให้สวย)
    metrics_path: /metrics   # <-- ใส่ตรงนี้
    static_configs:
      - targets:
          - 'node-server:5000'
          - 'node-server2:5000'
          - 'node-server3:5000'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):5000'
        target_label: instance
        replacement: '${1}'

  - job_name: 'mysql'
    metrics_path: /metrics 
    static_configs:
      - targets: ['mysqld_exporter:9104']
