services:
  reverseproxy:
    image: reverseproxy
    # container_name: reverseproxy
    build:
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    # ports:
    #   - 3000:3000
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/condf.d
    depends_on:
      - reverseproxy
    ports:  
      - 3000:3000
