version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tls.crt:/etc/nginx/ssl/fullchain.pem
      - ./tls.key:/etc/nginx/ssl/privkey.pem
      - ./secrets/.grafana.htpasswd:/etc/nginx/.grafana.htpasswd
    depends_on:
      - node-server
    networks:
      - monitor-net

  db:
    image: mysql:5.7.16
    container_name: mysql-container
    environment:    
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: my_db
      MYSQL_USER: root

    volumes:
      - mysql-data:/var/lib/mysql
      # - type: bind
      #   source: D:\\best\\xamppja\\tote
      #   target: /var/lib/mysql
    networks:
      - monitor-net
    command:
      - --performance_schema=ON

  mysqld_exporter:
    image: prom/mysqld-exporter
    command:
       - --config.my-cnf="/cfg/.my.cnf"
       - --mysqld.username=root:mypassword
       - --mysqld.address=db:3306
       - --collect.perf_schema.eventsstatements
    volumes:
       - "./.my.cnf:/cfg/.my.cnf"
    networks:
       - monitor-net
    depends_on:
      - db
   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: mypassword
    networks:
      - monitor-net
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis-container
    volumes:
      - redis-data:/data
    networks:
      - monitor-net

  node-server:
    build:
      context: .
    networks:
      - monitor-net
    depends_on:
      - db
    deploy:
      replicas: 3
    restart: always
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
    restart: always
    networks:
      - monitor-net
    
  node-exporter:
    image: prom/node-exporter:latest
    networks:
      - monitor-net
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    environment:
       GF_SERVER_HTTP_ADDR: "0.0.0.0"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitor-net
    restart: always

networks:
  monitor-net:
    driver: bridge

volumes:
  redis-data:
  prometheus_data:
  grafana_data:
  mysql-data:
