services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./tls.crt:/etc/nginx/ssl/fullchain.pem   # เปลี่ยนให้เป็นไฟล์เฉพาะ
      - ./tls.key:/etc/nginx/ssl/privkey.pem
    depends_on:
      - node-server
      - node-server2
      - node-server3

  db:
    image: mysql:5.7.16
    container_name: mysql-container
    environment:     # Set a strong root password
      MYSQL_ROOT_PASSWORD: mypassword   
      MYSQL_DATABASE: my_db
          # Optional: specify a default database      # Optional: password for the new user
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: D:\best\xamppja\tote
        target: /var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql-container          # Link to MySQL service
      PMA_USER: root                   # Optional: MySQL root user for phpMyAdmin
      PMA_PASSWORD: mypassword      # Optional: MySQL root password
    ports: 
     - "8081:80"    
  redis:
    image: redis:latest    # ใช้ Redis ล่าสุด
    container_name: redis-container
    ports:
      - "6379:6379"        # เปิดพอร์ต 6379 ให้เชื่อมต่อ Redis ได้จากภายนอก
    volumes:
      - redis-data:/data   # เก็บข้อมูล Redis ถาวร
  node-server:
    build: 
        context: .
    ports:
      - "5001:5000" 
  node-server2:               
    build: 
        context: .
    ports:
      - "5002:5000"
  node-server3:
    build: 
        context: .
    ports:
      - "5003:5000"
volumes:
     redis-data:           # Access phpMyAdmin at http://localhost:8080.