apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: best
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  source:
    path: TaskTracker-nginx
    repoURL: git@github.com:MANAPHAT56/FirstProject.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true