-

  name: Test aptitude update
  hosts: all
  become: true
  tasks:
    - name: Create FIxter file
      copy:
        src: /mnt/d/best/github/firstproject/TaskTracker-nginx/secrets
        dest:  /home/ubuntu/FirstProject/TaskTracker-nginx/ # โฟลเดอร์ปลายทาง
        owner: ubuntu
        group: root
        mode: '0755'