apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::739275443965:role/eksctl-fabulous-blues-unicorn-addon-iamservic-Role1-VXWmD7QhZTYB 