name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # หรือใช้ branch ที่คุณต้องการ
  pull_request:
    branches:
      - main  # หรือใช้ branch ที่คุณต้องการ

jobs:
  build:
    runs-on: ubuntu-latest  # ใช้เครื่อง Ubuntu สำหรับการ build

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Redis image
      - name: Build Redis image
        run: |
          docker build --platform linux/amd64,linux/arm64 -t redis-image:latest ./redis
          docker push redis-image:latest

      # Build and push Apache image
      - name: Build Apache image
        run: |
          docker build --platform linux/amd64,linux/arm64 -t apache-image:latest ./apache
          docker push apache-image:latest
