name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #htfhtj
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and push Docker images using Docker Compose
        run: |
          docker-compose -f /TaskTracker/docker-compose.yml build  # Build images based on your docker-compose.yml file
          docker-compose -f /TaskTracker/docker-compose.yml push   # Push images to Docker Hub
