name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker

      - name: Build Docker image for Node.js
        run: |
          docker build -t manapghat/node-server:latest ./TaskTracker
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push manaphat/node-server:latest
