name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image for Node.js
        run: |
          docker build -t manaphat/node-servernginx:grafana ./TaskTracker-nginx
      - name: Push Docker image to Docker Hub
        run: |
          docker push manaphat/node-servernginx:grafana
      - name: Update Trivy DB
        run: trivy db update          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: 'manaphat/node-servernginx:grafana'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'        
