name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Check out repository
       uses: actions/checkout@v2

     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
          username: ${{ MANAPHAT}}
          password: ${{ 18081978 }}

     - name: Build the Docker image
       run: docker build . --file ./TaskTracker/Dockerfile --tag myusername/myimagename:latest

     - name: Push the Docker image
       run: docker push myusername/myimagename:latest
