name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull Redis image
      - name: Pull Redis image
        run: |
          docker pull redis:latest

      # Build Redis image with multi-platform support
      - name: Build Redis image
        run: |
          docker buildx build --file ./redis/Dockerfile --tag manaphat/redis-image:latest

      # Pull Apache image
      - name: Pull Apache image
        run: |
          docker pull httpd:latest

      # Build Apache image with multi-platform support
      - name: Build Apache image
        run: |
          docker buildx build --file ./apache/Dockerfile --tag manaphat/apache-image:latest 
       #  docker build . --file ./TaskTracker/Dockerfile --tag manaphat/myimagename:latest
